[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sphinx~=8.2.3",
    "sphinx-rtd-theme==3.1.0",
    "sphinx-toolbox~=4.1.0",
]

[dependency-groups]
dev = [
    "sphinx-autobuild==2025.8.25",
]
